### ISSUE TITLE
Deep Dive into repo and create process flow diagram

### ISSUE THREAD

**Issue by vaibhavmehrotraml** [orcasound/ambient-sound-analysis#31]
Identify functions responsible for data download, data processing, transformation (the heavy math), and generate visualizable intermediate results. Review with @scottveirs 
```[tasklist]
### Tasks
- [ ] Understand the process flow of the existing database
- [ ] Identify specific mathematical transformations/calculations and review with domain experts
- [ ] Add any comments [here](https://github.com/orcasound/orca-hls-utils/issues/12) about audio file organization (HLS & FLAC) that could optimize future ambient noise analysis (e.g. make parallelization easier, or save costs in the long-run)
```

**Comment by vaibhavmehrotraml** [comment]
Checkout acoustic_util.py/apply_per_channel_energy

**Comment by zprice12** [comment]
Understand repo and process flow diagram created
