### ISSUE TITLE
Select and draw out MVP plans for mid/late February

### ISSUE THREAD

**Issue by vaibhavmehrotraml** [orcasound/ambient-sound-analysis#32]
```[tasklist]
### Tasks
- [ ] Estimate future tasks and timeline
- [ ] Classification vs Scaling of analysis
- [ ] Supervised vs Unsupervised
```

**Comment by zprice12** [comment]
Completed and on track
